"""
Seed 30 demo instruments into CalTrack Pro via the REST API.
Run: python seed_instruments.py
"""

import urllib.request
import urllib.error
import json
from datetime import date, timedelta

BASE = "http://localhost:8000/api"
SITE = "Demo"           # matches created_by / site name
TODAY = date(2026, 4, 6)

def d(offset_days):
    """Return an ISO date string relative to TODAY."""
    return (TODAY + timedelta(days=offset_days)).isoformat()


# ---------------------------------------------------------------------------
# 30 Instruments
# ---------------------------------------------------------------------------

INSTRUMENTS = [

    # ── PRESSURE TRANSMITTERS ───────────────────────────────────────────────

    {
        "tag_number": "PT-1001",
        "description": "Suction Header Pressure",
        "area": "Unit 1",
        "unit": "Train A",
        "instrument_type": "pressure",
        "manufacturer": "Endress+Hauser",
        "model": "Cerabar T PMC131",
        "serial_number": "EH-10019823",
        "measurement_lrv": 0.0,
        "measurement_urv": 1000.0,
        "engineering_units": "kPa",
        "output_type": "4_20ma",
        "calibration_interval_days": 365,
        "tolerance_type": "percent_span",
        "tolerance_value": 0.5,
        "num_test_points": 5,
        "criticality": "safety_critical",
        "status": "active",
        "last_calibration_date": d(-420),   # 420 days ago — overdue
        "last_calibration_result": "pass",
        "procedure_reference": "PROC-CAL-001",
        "created_by": SITE,
    },
    {
        "tag_number": "PT-1023",
        "description": "Feed Pump Discharge Pressure",
        "area": "Unit 1",
        "unit": "Train A",
        "instrument_type": "pressure",
        "manufacturer": "Rosemount",
        "model": "3051C",
        "serial_number": "RM-20481",
        "measurement_lrv": 0.0,
        "measurement_urv": 2500.0,
        "engineering_units": "kPa",
        "output_type": "hart",
        "calibration_interval_days": 180,
        "tolerance_type": "percent_span",
        "tolerance_value": 0.25,
        "num_test_points": 5,
        "criticality": "process_critical",
        "status": "active",
        "last_calibration_date": d(-210),   # overdue by 30 days
        "last_calibration_result": "fail",
        "procedure_reference": "PROC-CAL-001",
        "created_by": SITE,
    },
    {
        "tag_number": "PT-2001",
        "description": "Tank Farm Header Pressure",
        "area": "Tank Farm",
        "unit": "Storage",
        "instrument_type": "pressure",
        "manufacturer": "Yokogawa",
        "model": "EJA110A",
        "serial_number": "YO-58834",
        "measurement_lrv": 0.0,
        "measurement_urv": 500.0,
        "engineering_units": "kPa",
        "output_type": "4_20ma",
        "calibration_interval_days": 365,
        "tolerance_type": "percent_span",
        "tolerance_value": 0.5,
        "num_test_points": 5,
        "criticality": "standard",
        "status": "active",
        "last_calibration_date": d(-355),   # due in 10 days
        "last_calibration_result": "pass",
        "procedure_reference": "PROC-CAL-002",
        "created_by": SITE,
    },
    {
        "tag_number": "PT-2045",
        "description": "Compressor Suction Pressure",
        "area": "Compressor Area",
        "unit": "Compressor A",
        "instrument_type": "pressure",
        "manufacturer": "Endress+Hauser",
        "model": "Cerabar S PMP71",
        "serial_number": "EH-20093",
        "measurement_lrv": 0.0,
        "measurement_urv": 3000.0,
        "engineering_units": "kPa",
        "output_type": "hart",
        "calibration_interval_days": 365,
        "tolerance_type": "percent_span",
        "tolerance_value": 0.5,
        "num_test_points": 5,
        "criticality": "process_critical",
        "status": "active",
        "last_calibration_date": d(-180),   # current — due in 185 days
        "last_calibration_result": "pass",
        "created_by": SITE,
    },
    {
        "tag_number": "PT-3001",
        "description": "Separator Outlet Pressure",
        "area": "Unit 3",
        "unit": "Separator",
        "instrument_type": "pressure",
        "manufacturer": "ABB",
        "model": "2600T Series",
        "serial_number": "AB-77441",
        "measurement_lrv": 0.0,
        "measurement_urv": 800.0,
        "engineering_units": "kPa",
        "output_type": "4_20ma",
        "calibration_interval_days": 180,
        "tolerance_type": "percent_span",
        "tolerance_value": 1.0,
        "num_test_points": 5,
        "criticality": "standard",
        "status": "active",
        "last_calibration_date": d(-270),   # overdue by 90 days
        "last_calibration_result": "marginal",
        "created_by": SITE,
    },

    # ── TEMPERATURE TRANSMITTERS ────────────────────────────────────────────

    {
        "tag_number": "TT-1001",
        "description": "Reactor Outlet Temperature",
        "area": "Unit 1",
        "unit": "Reactor",
        "instrument_type": "temperature",
        "manufacturer": "Endress+Hauser",
        "model": "iTEMP TMT82",
        "serial_number": "EH-TT1001",
        "measurement_lrv": 0.0,
        "measurement_urv": 500.0,
        "engineering_units": "degC",
        "output_type": "hart",
        "calibration_interval_days": 365,
        "tolerance_type": "absolute",
        "tolerance_value": 1.0,
        "num_test_points": 5,
        "criticality": "safety_critical",
        "status": "active",
        "last_calibration_date": d(-60),    # current — 9 months remaining
        "last_calibration_result": "pass",
        "procedure_reference": "PROC-CAL-003",
        "created_by": SITE,
    },
    {
        "tag_number": "TT-1024",
        "description": "Heat Exchanger Shell Inlet",
        "area": "Unit 1",
        "unit": "HX-101",
        "instrument_type": "temperature",
        "manufacturer": "Rosemount",
        "model": "644H",
        "serial_number": "RM-TT1024",
        "measurement_lrv": 0.0,
        "measurement_urv": 300.0,
        "engineering_units": "degC",
        "output_type": "4_20ma",
        "calibration_interval_days": 365,
        "tolerance_type": "absolute",
        "tolerance_value": 1.5,
        "num_test_points": 5,
        "criticality": "process_critical",
        "status": "active",
        "last_calibration_date": d(-400),   # overdue by 35 days
        "last_calibration_result": "fail",
        "created_by": SITE,
    },
    {
        "tag_number": "TT-2001",
        "description": "Distillation Column Top Temperature",
        "area": "Unit 2",
        "unit": "Column C-201",
        "instrument_type": "temperature",
        "manufacturer": "Yokogawa",
        "model": "YTA510",
        "serial_number": "YO-TT2001",
        "measurement_lrv": 20.0,
        "measurement_urv": 250.0,
        "engineering_units": "degC",
        "output_type": "hart",
        "calibration_interval_days": 365,
        "tolerance_type": "absolute",
        "tolerance_value": 1.0,
        "num_test_points": 5,
        "criticality": "process_critical",
        "status": "active",
        "last_calibration_date": d(-90),    # current
        "last_calibration_result": "pass",
        "created_by": SITE,
    },
    {
        "tag_number": "TT-2034",
        "description": "Reboiler Outlet Temperature",
        "area": "Unit 2",
        "unit": "Column C-201",
        "instrument_type": "temperature",
        "manufacturer": "Endress+Hauser",
        "model": "iTEMP TMT85",
        "serial_number": "EH-TT2034",
        "measurement_lrv": 50.0,
        "measurement_urv": 350.0,
        "engineering_units": "degC",
        "output_type": "hart",
        "calibration_interval_days": 365,
        "tolerance_type": "absolute",
        "tolerance_value": 1.0,
        "num_test_points": 5,
        "criticality": "process_critical",
        "status": "active",
        "last_calibration_date": d(-356),   # due in 9 days
        "last_calibration_result": "pass",
        "created_by": SITE,
    },
    {
        "tag_number": "TT-3001",
        "description": "Furnace Outlet Temperature",
        "area": "Unit 3",
        "unit": "Furnace F-301",
        "instrument_type": "temperature",
        "manufacturer": "Rosemount",
        "model": "848T",
        "serial_number": "RM-TT3001",
        "measurement_lrv": 100.0,
        "measurement_urv": 900.0,
        "engineering_units": "degC",
        "output_type": "hart",
        "calibration_interval_days": 180,
        "tolerance_type": "absolute",
        "tolerance_value": 2.0,
        "num_test_points": 7,
        "criticality": "safety_critical",
        "status": "active",
        "last_calibration_date": d(-280),   # overdue — 100 days over
        "last_calibration_result": "fail",
        "procedure_reference": "PROC-CAL-CRIT-001",
        "created_by": SITE,
    },
    {
        "tag_number": "TT-4001",
        "description": "Cooling Water Return Temperature",
        "area": "Utilities",
        "unit": "CW System",
        "instrument_type": "temperature",
        "manufacturer": "ABB",
        "model": "TSP341",
        "serial_number": "AB-TT4001",
        "measurement_lrv": 10.0,
        "measurement_urv": 60.0,
        "engineering_units": "degC",
        "output_type": "4_20ma",
        "calibration_interval_days": 730,
        "tolerance_type": "absolute",
        "tolerance_value": 2.0,
        "num_test_points": 3,
        "criticality": "non_critical",
        "status": "active",
        "created_by": SITE,
    },

    # ── FLOW TRANSMITTERS ────────────────────────────────────────────────────

    {
        "tag_number": "FT-1001",
        "description": "Feed Flow",
        "area": "Unit 1",
        "unit": "Train A",
        "instrument_type": "flow",
        "manufacturer": "Endress+Hauser",
        "model": "Promag 53W",
        "serial_number": "EH-FT1001",
        "measurement_lrv": 0.0,
        "measurement_urv": 500.0,
        "engineering_units": "m3/h",
        "output_type": "hart",
        "calibration_interval_days": 365,
        "tolerance_type": "percent_reading",
        "tolerance_value": 0.5,
        "num_test_points": 5,
        "criticality": "process_critical",
        "status": "active",
        "last_calibration_date": d(-120),   # current
        "last_calibration_result": "pass",
        "procedure_reference": "PROC-CAL-004",
        "created_by": SITE,
    },
    {
        "tag_number": "FT-1045",
        "description": "Recycle Flow",
        "area": "Unit 1",
        "unit": "Recycle Loop",
        "instrument_type": "flow",
        "manufacturer": "Yokogawa",
        "model": "ADMAG AXF",
        "serial_number": "YO-FT1045",
        "measurement_lrv": 0.0,
        "measurement_urv": 200.0,
        "engineering_units": "m3/h",
        "output_type": "hart",
        "calibration_interval_days": 365,
        "tolerance_type": "percent_reading",
        "tolerance_value": 1.0,
        "num_test_points": 5,
        "criticality": "standard",
        "status": "active",
        "last_calibration_date": d(-353),   # due in 12 days
        "last_calibration_result": "marginal",
        "created_by": SITE,
    },
    {
        "tag_number": "FT-2001",
        "description": "Product Export Flow",
        "area": "Unit 2",
        "unit": "Product Line",
        "instrument_type": "flow",
        "manufacturer": "Micro Motion",
        "model": "ELITE CMF300M",
        "serial_number": "MM-FT2001",
        "measurement_lrv": 0.0,
        "measurement_urv": 1000.0,
        "engineering_units": "m3/h",
        "output_type": "hart",
        "calibration_interval_days": 365,
        "tolerance_type": "percent_reading",
        "tolerance_value": 0.1,
        "num_test_points": 7,
        "criticality": "process_critical",
        "status": "active",
        "last_calibration_date": d(-200),   # current
        "last_calibration_result": "pass",
        "created_by": SITE,
    },
    {
        "tag_number": "FT-3001",
        "description": "HP Steam Supply Flow",
        "area": "Utilities",
        "unit": "Steam System",
        "instrument_type": "flow",
        "manufacturer": "Rosemount",
        "model": "3051SF",
        "serial_number": "RM-FT3001",
        "measurement_lrv": 0.0,
        "measurement_urv": 50.0,
        "engineering_units": "t/h",
        "output_type": "hart",
        "calibration_interval_days": 180,
        "tolerance_type": "percent_span",
        "tolerance_value": 1.0,
        "num_test_points": 5,
        "criticality": "process_critical",
        "status": "active",
        "last_calibration_date": d(-210),   # overdue by 30 days
        "last_calibration_result": "fail",
        "created_by": SITE,
    },
    {
        "tag_number": "FT-4001",
        "description": "Cooling Water Supply Flow",
        "area": "Utilities",
        "unit": "CW System",
        "instrument_type": "flow",
        "manufacturer": "Endress+Hauser",
        "model": "Promag H 100",
        "serial_number": "EH-FT4001",
        "measurement_lrv": 0.0,
        "measurement_urv": 2000.0,
        "engineering_units": "m3/h",
        "output_type": "4_20ma",
        "calibration_interval_days": 730,
        "tolerance_type": "percent_span",
        "tolerance_value": 2.0,
        "num_test_points": 3,
        "criticality": "standard",
        "status": "active",
        "last_calibration_date": d(-400),   # current (730 day interval)
        "last_calibration_result": "pass",
        "created_by": SITE,
    },

    # ── LEVEL TRANSMITTERS ───────────────────────────────────────────────────

    {
        "tag_number": "LT-1001",
        "description": "Feed Drum Level",
        "area": "Unit 1",
        "unit": "V-101",
        "instrument_type": "level",
        "manufacturer": "Rosemount",
        "model": "5600",
        "serial_number": "RM-LT1001",
        "measurement_lrv": 0.0,
        "measurement_urv": 100.0,
        "engineering_units": "%",
        "output_type": "hart",
        "calibration_interval_days": 365,
        "tolerance_type": "percent_span",
        "tolerance_value": 0.5,
        "num_test_points": 5,
        "criticality": "safety_critical",
        "status": "active",
        "last_calibration_date": d(-150),   # current — 215 days remaining
        "last_calibration_result": "pass",
        "procedure_reference": "PROC-CAL-005",
        "created_by": SITE,
    },
    {
        "tag_number": "LT-1023",
        "description": "Reflux Drum Level",
        "area": "Unit 1",
        "unit": "V-102",
        "instrument_type": "level",
        "manufacturer": "Endress+Hauser",
        "model": "FMB70",
        "serial_number": "EH-LT1023",
        "measurement_lrv": 0.0,
        "measurement_urv": 100.0,
        "engineering_units": "%",
        "output_type": "hart",
        "calibration_interval_days": 365,
        "tolerance_type": "percent_span",
        "tolerance_value": 0.5,
        "num_test_points": 5,
        "criticality": "process_critical",
        "status": "active",
        "last_calibration_date": d(-358),   # due in 7 days
        "last_calibration_result": "pass",
        "created_by": SITE,
    },
    {
        "tag_number": "LT-2001",
        "description": "Distillation Column Sump Level",
        "area": "Unit 2",
        "unit": "Column C-201",
        "instrument_type": "level",
        "manufacturer": "Yokogawa",
        "model": "DY015",
        "serial_number": "YO-LT2001",
        "measurement_lrv": 0.0,
        "measurement_urv": 100.0,
        "engineering_units": "%",
        "output_type": "hart",
        "calibration_interval_days": 365,
        "tolerance_type": "percent_span",
        "tolerance_value": 1.0,
        "num_test_points": 5,
        "criticality": "process_critical",
        "status": "active",
        "last_calibration_date": d(-395),   # overdue by 30 days
        "last_calibration_result": "marginal",
        "created_by": SITE,
    },
    {
        "tag_number": "LT-3001",
        "description": "Three-Phase Separator Level",
        "area": "Unit 3",
        "unit": "V-301",
        "instrument_type": "level",
        "manufacturer": "Rosemount",
        "model": "5408",
        "serial_number": "RM-LT3001",
        "measurement_lrv": 0.0,
        "measurement_urv": 100.0,
        "engineering_units": "%",
        "output_type": "hart",
        "calibration_interval_days": 365,
        "tolerance_type": "percent_span",
        "tolerance_value": 0.5,
        "num_test_points": 5,
        "criticality": "process_critical",
        "status": "active",
        "last_calibration_date": d(-240),   # current
        "last_calibration_result": "pass",
        "created_by": SITE,
    },

    # ── ANALYSERS ────────────────────────────────────────────────────────────

    {
        "tag_number": "AT-1001",
        "description": "Effluent pH Analyser",
        "area": "Unit 1",
        "unit": "Effluent Treatment",
        "instrument_type": "analyser",
        "manufacturer": "Endress+Hauser",
        "model": "Liquiline CM442",
        "serial_number": "EH-AT1001",
        "measurement_lrv": 0.0,
        "measurement_urv": 14.0,
        "engineering_units": "pH",
        "output_type": "digital",
        "calibration_interval_days": 90,
        "tolerance_type": "absolute",
        "tolerance_value": 0.1,
        "num_test_points": 3,
        "criticality": "standard",
        "status": "active",
        "last_calibration_date": d(-120),   # overdue by 30 days
        "last_calibration_result": "fail",
        "procedure_reference": "PROC-CAL-ANALYSER-001",
        "created_by": SITE,
    },
    {
        "tag_number": "AT-2001",
        "description": "Flue Gas O₂ Analyser",
        "area": "Unit 2",
        "unit": "Heater H-201",
        "instrument_type": "analyser",
        "manufacturer": "ABB",
        "model": "AZ20",
        "serial_number": "AB-AT2001",
        "measurement_lrv": 0.0,
        "measurement_urv": 25.0,
        "engineering_units": "% vol",
        "output_type": "digital",
        "calibration_interval_days": 180,
        "tolerance_type": "absolute",
        "tolerance_value": 0.5,
        "num_test_points": 3,
        "criticality": "process_critical",
        "status": "active",
        "last_calibration_date": d(-90),    # current — 90 days remaining
        "last_calibration_result": "pass",
        "created_by": SITE,
    },
    {
        "tag_number": "AT-3001",
        "description": "Gas Chromatograph — Compressor Feed",
        "area": "Compressor Area",
        "unit": "K-301",
        "instrument_type": "analyser",
        "manufacturer": "Emerson",
        "model": "Daniel 2350",
        "serial_number": "EM-AT3001",
        "measurement_lrv": 0.0,
        "measurement_urv": 100.0,
        "engineering_units": "% mol",
        "output_type": "digital",
        "calibration_interval_days": 365,
        "tolerance_type": "percent_span",
        "tolerance_value": 1.0,
        "num_test_points": 3,
        "criticality": "process_critical",
        "status": "active",
        "last_calibration_date": d(-352),   # due in 13 days
        "last_calibration_result": "pass",
        "created_by": SITE,
    },

    # ── SWITCHES ────────────────────────────────────────────────────────────

    {
        "tag_number": "PSH-1001",
        "description": "Reactor High Pressure Switch",
        "area": "Unit 1",
        "unit": "Reactor",
        "instrument_type": "switch",
        "manufacturer": "Gems Sensors",
        "model": "9200RM",
        "serial_number": "GS-PSH1001",
        "measurement_lrv": 0.0,
        "measurement_urv": 2000.0,
        "engineering_units": "kPa",
        "output_type": "digital",
        "calibration_interval_days": 365,
        "tolerance_type": "absolute",
        "tolerance_value": 10.0,
        "num_test_points": 3,
        "criticality": "safety_critical",
        "status": "active",
        "last_calibration_date": d(-200),   # current
        "last_calibration_result": "pass",
        "procedure_reference": "PROC-CAL-SAFETY-001",
        "created_by": SITE,
    },
    {
        "tag_number": "LSH-2001",
        "description": "Column Sump High Level Switch",
        "area": "Unit 2",
        "unit": "Column C-201",
        "instrument_type": "switch",
        "manufacturer": "Magnetrol",
        "model": "E3 Modulevel",
        "serial_number": "MG-LSH2001",
        "measurement_lrv": 0.0,
        "measurement_urv": 100.0,
        "engineering_units": "%",
        "output_type": "digital",
        "calibration_interval_days": 365,
        "tolerance_type": "absolute",
        "tolerance_value": 2.0,
        "num_test_points": 3,
        "criticality": "safety_critical",
        "status": "active",
        "created_by": SITE,
    },
    {
        "tag_number": "TSH-3001",
        "description": "Furnace High Temperature Switch",
        "area": "Unit 3",
        "unit": "Furnace F-301",
        "instrument_type": "switch",
        "manufacturer": "Thermon",
        "model": "TCS-90",
        "serial_number": "TH-TSH3001",
        "measurement_lrv": 0.0,
        "measurement_urv": 1000.0,
        "engineering_units": "degC",
        "output_type": "digital",
        "calibration_interval_days": 365,
        "tolerance_type": "absolute",
        "tolerance_value": 5.0,
        "num_test_points": 3,
        "criticality": "safety_critical",
        "status": "active",
        "last_calibration_date": d(-100),   # current — 265 days remaining
        "last_calibration_result": "pass",
        "procedure_reference": "PROC-CAL-SAFETY-001",
        "created_by": SITE,
    },

    # ── CONTROL VALVES ────────────────────────────────────────────────────────

    {
        "tag_number": "CV-1001",
        "description": "Feed Flow Control Valve",
        "area": "Unit 1",
        "unit": "Train A",
        "instrument_type": "valve",
        "manufacturer": "Fisher",
        "model": "GX Control Valve",
        "serial_number": "FI-CV1001",
        "measurement_lrv": 0.0,
        "measurement_urv": 100.0,
        "engineering_units": "%",
        "output_type": "4_20ma",
        "calibration_interval_days": 365,
        "tolerance_type": "percent_span",
        "tolerance_value": 1.0,
        "num_test_points": 5,
        "criticality": "process_critical",
        "status": "active",
        "last_calibration_date": d(-45),    # current — 320 days remaining
        "last_calibration_result": "pass",
        "created_by": SITE,
    },
    {
        "tag_number": "CV-2001",
        "description": "Reflux Flow Control Valve",
        "area": "Unit 2",
        "unit": "Column C-201",
        "instrument_type": "valve",
        "manufacturer": "Emerson",
        "model": "FIELDVUE DVC6200",
        "serial_number": "EM-CV2001",
        "measurement_lrv": 0.0,
        "measurement_urv": 100.0,
        "engineering_units": "%",
        "output_type": "hart",
        "calibration_interval_days": 365,
        "tolerance_type": "percent_span",
        "tolerance_value": 1.0,
        "num_test_points": 5,
        "criticality": "process_critical",
        "status": "active",
        "last_calibration_date": d(-354),   # due in 11 days
        "last_calibration_result": "pass",
        "created_by": SITE,
    },
    {
        "tag_number": "PCV-3001",
        "description": "Separator Pressure Control Valve",
        "area": "Unit 3",
        "unit": "V-301",
        "instrument_type": "valve",
        "manufacturer": "Samson",
        "model": "Series 3730",
        "serial_number": "SA-PCV3001",
        "measurement_lrv": 0.0,
        "measurement_urv": 100.0,
        "engineering_units": "%",
        "output_type": "hart",
        "calibration_interval_days": 180,
        "tolerance_type": "percent_span",
        "tolerance_value": 2.0,
        "num_test_points": 5,
        "criticality": "process_critical",
        "status": "active",
        "last_calibration_date": d(-220),   # overdue by 40 days
        "last_calibration_result": "fail",
        "created_by": SITE,
    },

    # ── SPARE / OUT-OF-SERVICE ───────────────────────────────────────────────

    {
        "tag_number": "PT-9001",
        "description": "Spare Pressure Transmitter",
        "area": "Warehouse",
        "unit": "Spares",
        "instrument_type": "pressure",
        "manufacturer": "Rosemount",
        "model": "3051CA",
        "serial_number": "RM-SPARE-001",
        "measurement_lrv": 0.0,
        "measurement_urv": 1000.0,
        "engineering_units": "kPa",
        "output_type": "4_20ma",
        "calibration_interval_days": 730,
        "tolerance_type": "percent_span",
        "tolerance_value": 0.5,
        "num_test_points": 5,
        "criticality": "standard",
        "status": "spare",
        "last_calibration_date": d(-300),   # current (730-day interval)
        "last_calibration_result": "pass",
        "created_by": SITE,
    },
    {
        "tag_number": "FT-9001",
        "description": "Decommissioned Vortex Meter",
        "area": "Unit 1",
        "unit": "Train A",
        "instrument_type": "flow",
        "manufacturer": "Endress+Hauser",
        "model": "Prowirl 200",
        "serial_number": "EH-DCOM-001",
        "measurement_lrv": 0.0,
        "measurement_urv": 300.0,
        "engineering_units": "m3/h",
        "output_type": "hart",
        "calibration_interval_days": 365,
        "tolerance_type": "percent_reading",
        "tolerance_value": 1.0,
        "num_test_points": 3,
        "criticality": "standard",
        "status": "out_of_service",
        "last_calibration_date": d(-500),
        "last_calibration_result": "fail",
        "created_by": SITE,
    },
]


# ---------------------------------------------------------------------------
# Send to API
# ---------------------------------------------------------------------------

def post_json(url, data):
    body = json.dumps(data).encode()
    req = urllib.request.Request(
        url, data=body,
        headers={"Content-Type": "application/json"},
        method="POST",
    )
    try:
        with urllib.request.urlopen(req, timeout=10) as resp:
            return resp.status, json.loads(resp.read())
    except urllib.error.HTTPError as e:
        return e.code, json.loads(e.read())


created = 0
skipped = 0
errors   = []

for instr in INSTRUMENTS:
    tag = instr["tag_number"]
    code, body = post_json(f"{BASE}/instruments", instr)
    if code == 201:
        print(f"  ✓  {tag:<14}  created  (id={body['id'][:8]}…)")
        created += 1
    elif code == 409:
        print(f"  –  {tag:<14}  already exists, skipping")
        skipped += 1
    else:
        msg = body.get("detail", str(body))
        print(f"  ✗  {tag:<14}  ERROR {code}: {msg}")
        errors.append((tag, code, msg))

print()
print(f"Done. Created: {created}  Skipped: {skipped}  Errors: {len(errors)}")
if errors:
    for t, c, m in errors:
        print(f"     {t}: {c} — {m}")
